# frozen_string_literal: true

require_relative "user"
require_relative "post"

# Example usage of Mongoid models
# This file demonstrates the accessor methods generated by `field` declarations
# ruby-lsp-mongoid should provide go-to-definition and autocomplete for these methods

user = User.new

# Field accessors generated by `field :name, type: String`
user.name = "John Doe"
puts user.name

# Field accessors generated by `field :email, type: String`
user.email = "john@example.com"
puts user.email

# Field accessors generated by `field :age, type: Integer`
user.age = 30
puts user.age

# Field accessors generated by `field :active, type: Boolean`
user.active = true
puts user.active

# Field accessors generated by `field :score, type: Float`
user.score = 95.5
puts user.score

# Field accessors generated by `field :metadata, type: Hash`
user.metadata = { role: "admin" }
puts user.metadata

# Field accessors generated by `field :tags, type: Array`
user.tags = %w[ruby mongodb]
puts user.tags

# Field accessors generated by `field :birthday, type: Date`
user.birthday = Date.new(1990, 1, 15)
puts user.birthday

# Field accessors generated by `field :last_login_at, type: Time`
user.last_login_at = Time.now
puts user.last_login_at

# Association accessors generated by `has_many :posts`
user.posts = []
puts user.posts

user.post_ids = []
puts user.post_ids

# Association accessors generated by `has_one :profile`
user.profile = nil
puts user.profile

user.build_profile
user.create_profile
user.create_profile!

# ---

post = Post.new

# Field accessors for Post model
post.title = "Hello World"
post.body = "This is my first post"
post.slug = "hello-world"
post.published = true
post.view_count = 100
post.published_at = DateTime.now

puts post.title
puts post.body
puts post.slug
puts post.published
puts post.view_count
puts post.published_at
puts post.likes

# Association accessors generated by `has_and_belongs_to_many :categories`
post.categories = []
puts post.categories

post.category_ids = []
puts post.category_ids

# Association accessors generated by `belongs_to :user`
post.user = nil
puts post.user

post.build_user
post.create_user

# Embedded document
comment = Comment.new
comment.content = "Great post!"
comment.author_name = "Jane"

author_info = AuthorInfo.new
author_info.bio = "Ruby developer"
author_info.website = "https://example.com"
